name: .NET Tests

on:
  push:
    branches:
      - main  # Запускать тесты при коммите в ветку main (можно указать другую ветку)
  pull_request:
    branches:
      - main  # Запускать тесты при создании Pull Request на main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Укажите нужную версию .NET, например, 7.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal
